//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int ID { get; set; }
        public Nullable<int> Party { get; set; }
        public Nullable<int> Counter_Party { get; set; }
        public Nullable<int> Instrument_ID { get; set; }
    
        public virtual instrument instrument { get; set; }
        public virtual LegalEntity LegalEntity { get; set; }
        public virtual LegalEntity LegalEntity1 { get; set; }
    }
}
